# Generated by Django 4.2.4 on 2024-03-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='User',
        ),
    ]
