# Generated by Django 4.2.4 on 2024-03-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
